require 'serialize/controls/text'
require 'serialize/controls/raw_data'
require 'serialize/controls/serializer'
require 'serialize/controls/instance'
require 'serialize/controls/no_serializer'
require 'serialize/controls/no_serializer_methods'
require 'serialize/controls/no_format'
require 'serialize/controls/no_format_methods'
